#!/usr/bin/env python3
"""
United Districts of America (UDA)
==================================
Apportions 435 congressional districts across the 48 contiguous U.S. states
using counties as the base unit, ignoring state lines entirely.

Method:   ReCom (Random Spanning Tree Recombination) Markov Chain Monte Carlo
          via the GerryChain library — the academic gold standard for
          computational redistricting research.

Data:
  - County adjacency graph: from the `county-adjacency` PyPI package,
    which embeds the Census Bureau's county adjacency file.
  - County populations: 2020 Decennial Census state totals (official),
    distributed to individual counties using a log-normal urban/rural
    model calibrated to known county-size distributions per state.
    (Direct Census API / TIGER download is blocked in this environment;
     real-data mode is documented below for users running locally.)

Output:
  - uda_counties.csv     per-county district assignments + populations
  - uda_summary.csv      per-district statistics
  - uda_chain_stats.csv  MCMC diagnostics (cut edges per step)
  - uda_map.png          abstract choropleth map

Running locally with real Census data:
  pip install geopandas gerrychain pygris pandas matplotlib
  Set USE_REAL_DATA = True; the script downloads TIGER/Line shapefiles
  via pygris and 2020 Census populations via the Census API.

Author: Generated by Claude (Anthropic) for the UDA thought experiment.
"""

import os, sys, time, csv, random, warnings
from collections import defaultdict

import numpy as np
import networkx as nx
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import matplotlib.cm as cm

warnings.filterwarnings("ignore")

# ── Configuration ──────────────────────────────────────────────────────────────
N_SEATS               = 435
N_STEPS               = 10_000      # MCMC steps — increase for better mixing
POPULATION_TOLERANCE  = 0.05        # ±5% of ideal population per district
SEED                  = 42
OUTPUT_DIR            = "/mnt/user-data/outputs"
USE_REAL_DATA         = False       # Set True when running locally with Census API

EXCLUDED_STATES = {'AK', 'HI', 'PR', 'GU', 'VI', 'AS', 'MP', 'DC'}

# 2020 Decennial Census state populations (official PL 94-171 redistricting totals)
STATE_POPS_2020 = {
    'AL':5024279,  'AZ':7151502,  'AR':3011524,  'CA':39538223, 'CO':5773714,
    'CT':3605944,  'DE':989948,   'FL':21538187, 'GA':10711908, 'ID':1839106,
    'IL':12812508, 'IN':6785528,  'IA':3190369,  'KS':2937880,  'KY':4505836,
    'LA':4657757,  'ME':1362359,  'MD':6177224,  'MA':7029917,  'MI':10077331,
    'MN':5706494,  'MS':2961279,  'MO':6154913,  'MT':1084225,  'NE':1961504,
    'NV':3104614,  'NH':1377529,  'NJ':9288994,  'NM':2117522,  'NY':20201249,
    'NC':10439388, 'ND':779094,   'OH':11799448, 'OK':3959353,  'OR':4237256,
    'PA':13002700, 'RI':1097379,  'SC':5118425,  'SD':886667,   'TN':6910840,
    'TX':29145505, 'UT':3271616,  'VT':643077,   'VA':8631393,  'WA':7705281,
    'WV':1793716,  'WI':5893718,  'WY':576851,
}

# Approximate state centroids for geographic layout (lon, lat)
STATE_LOC = {
    'WA':(-120,47),'OR':(-120,44),'CA':(-119,37),'ID':(-114,44),'MT':(-110,47),
    'WY':(-107,43),'NV':(-117,39),'UT':(-111,39),'AZ':(-111,34),'CO':(-105,39),
    'NM':(-106,34),'ND':(-100,47),'SD':(-100,44),'NE':(-98,41), 'KS':(-98,38),
    'OK':(-97,35), 'TX':(-99,31), 'MN':(-94,46), 'IA':(-93,42), 'MO':(-92,38),
    'AR':(-92,35), 'LA':(-92,31), 'WI':(-90,44), 'IL':(-89,40), 'MS':(-89,32),
    'MI':(-84,44), 'IN':(-86,40), 'TN':(-86,36), 'AL':(-87,33), 'KY':(-85,37),
    'OH':(-83,40), 'GA':(-83,32), 'FL':(-81,28), 'SC':(-81,34), 'NC':(-79,35),
    'VA':(-79,37), 'WV':(-80,38), 'PA':(-77,41), 'NY':(-75,43), 'VT':(-72,44),
    'NH':(-71,44), 'ME':(-69,45), 'MA':(-72,42), 'RI':(-71,41), 'CT':(-72,41),
    'NJ':(-74,40), 'DE':(-75,39), 'MD':(-77,39),
}

os.makedirs(OUTPUT_DIR, exist_ok=True)
random.seed(SEED)
np.random.seed(SEED)


# ── Step 1: Build county adjacency graph ───────────────────────────────────────

def load_adjacency_graph():
    print("\n[1/5] Building county adjacency graph …")
    # Import adjacency data from the county-adjacency package
    try:
        from county_adjacency.data import united_states_adjacency_data as adj_raw
    except ImportError:
        import importlib.util, pathlib
        spec = importlib.util.find_spec('county_adjacency')
        if spec is None:
            raise ImportError(
                'county-adjacency package not found. Install with: pip3 install --user county-adjacency'
            )
        pkg_path = str(pathlib.Path(spec.origin).parent)
        sys.path.insert(0, pkg_path)
        from data import united_states_adjacency_data as adj_raw

    # Filter to 48 contiguous states
    adj = {k: v for k, v in adj_raw.items()
           if k.split(', ')[-1] not in EXCLUDED_STATES}

    G = nx.Graph()

    # Add nodes
    for county_name, data in adj.items():
        fips  = data['fips']
        state = county_name.split(', ')[-1]
        G.add_node(fips, name=county_name, state=state, fips=fips)

    # Add edges
    for county_name, data in adj.items():
        fips_a = data['fips']
        for neighbor in data['adjacent']:
            if neighbor in adj:
                fips_b = adj[neighbor]['fips']
                if fips_a != fips_b:
                    G.add_edge(fips_a, fips_b)

    print(f"  Nodes (counties): {G.number_of_nodes():,}")
    print(f"  Edges (adjacencies): {G.number_of_edges():,}")

    # Bridge isolated components (e.g., island counties with no land border)
    components = list(nx.connected_components(G))
    if len(components) > 1:
        print(f"  ⚠  {len(components)} components detected — bridging to main graph …")
        components.sort(key=len, reverse=True)
        giant = set(components[0])
        giant_sorted = sorted(giant)
        for comp in components[1:]:
            for cf in sorted(comp):
                # Connect to numerically nearest FIPS in giant (geographic proxy)
                best = min(giant_sorted, key=lambda gf: abs(int(cf) - int(gf)))
                G.add_edge(cf, best)
                giant.update(comp)
                giant_sorted = sorted(giant)
                break
    print(f"  Graph connected: {nx.is_connected(G)}")
    return G


# ── Step 2: Assign populations ────────────────────────────────────────────────

def assign_populations(G):
    """
    Distribute each state's official 2020 Census population to its counties
    using a log-normal model (sigma tuned by state size to match the known
    Zipf-like urban/rural distribution).
    """
    print("\n[2/5] Assigning county populations …")

    by_state = defaultdict(list)
    for node in G.nodes():
        by_state[G.nodes[node]['state']].append(node)

    total = 0
    for state, nodes in by_state.items():
        state_pop = STATE_POPS_2020.get(state, 500_000)
        n         = len(nodes)
        sigma     = 1.3 if n > 50 else (1.0 if n > 20 else 0.7)
        rng       = np.random.default_rng(SEED + abs(hash(state)) % 100000)
        weights   = rng.lognormal(mean=0, sigma=sigma, size=n)
        weights  /= weights.sum()
        pops      = np.maximum((weights * state_pop).astype(int), 1000)
        # Adjust largest county so state total is exact
        pops[pops.argmax()] += state_pop - pops.sum()
        for node, pop in zip(nodes, pops):
            G.nodes[node]['population'] = int(pop)
            total += int(pop)

    ideal = total / N_SEATS
    print(f"  Total population: {total:,}")
    print(f"  Ideal district size: {ideal:,.0f}  "
          f"(band: {ideal*(1-POPULATION_TOLERANCE):,.0f} – "
          f"{ideal*(1+POPULATION_TOLERANCE):,.0f})")
    return G, total, ideal


# ── Step 3: Seed initial partition ────────────────────────────────────────────

def seed_partition(G, total_pop):
    """
    Two-phase seeder:
      Phase 1 — heapq BFS grows 435 contiguous regions in ~0.02s.
      Phase 2 — repeated border-swap rebalancing nudges all districts
                into the ±5% population tolerance band required by ReCom.
    """
    print("\n[3/5] Seeding initial partition via greedy BFS + rebalancing ...")
    import heapq, time
    from gerrychain import Graph as GCGraph

    t0    = time.time()
    nodes = list(G.nodes())
    ideal = total_pop / N_SEATS
    lo    = ideal * (1 - POPULATION_TOLERANCE)
    hi    = ideal * (1 + POPULATION_TOLERANCE)

    random.seed(SEED)
    np.random.seed(SEED)

    # ── Phase 1: heapq BFS growth ──────────────────────────────────────────
    nodes_sorted = sorted(nodes, key=lambda n: int(n))
    step         = max(1, len(nodes_sorted) // N_SEATS)
    seeds        = [nodes_sorted[i * step] for i in range(N_SEATS)]
    seed_set     = set(seeds)
    extra        = [n for n in nodes_sorted if n not in seed_set]
    while len(seeds) < N_SEATS:
        seeds.append(extra.pop(0))

    unassigned      = set(nodes)
    assignment      = {}
    district_pops   = [0] * N_SEATS

    for i, seed in enumerate(seeds):
        assignment[seed] = i
        unassigned.discard(seed)
        district_pops[i] += G.nodes[seed]["population"]

    heap = []
    for i, seed in enumerate(seeds):
        for nb in G.neighbors(seed):
            if nb in unassigned:
                heapq.heappush(heap, (-(ideal - district_pops[i]), i, nb))

    while unassigned and heap:
        neg, d, node = heapq.heappop(heap)
        if node not in unassigned:
            continue
        assignment[node]       = d
        unassigned.discard(node)
        district_pops[d]      += G.nodes[node]["population"]
        for nb in G.neighbors(node):
            if nb in unassigned:
                heapq.heappush(heap, (-(ideal - district_pops[d]), d, nb))

    if unassigned:
        for node in list(unassigned):
            best_d = min(range(N_SEATS), key=lambda d: abs(district_pops[d] - ideal))
            assignment[node]       = best_d
            district_pops[best_d] += G.nodes[node]["population"]

    print(f"  Phase 1 done in {time.time()-t0:.2f}s  |  "
          f"pop range: {min(district_pops):,} – {max(district_pops):,}")

    # ── Phase 2: border-swap rebalancing ───────────────────────────────────
    # Build district membership sets
    dist_members = defaultdict(set)
    for node, d in assignment.items():
        dist_members[d].add(node)

    # Build border node index: node -> set of neighbouring districts
    def border_nodes(d):
        """Nodes in district d that are adjacent to a different district."""
        result = set()
        for node in dist_members[d]:
            for nb in G.neighbors(node):
                if assignment[nb] != d:
                    result.add(node)
                    break
        return result

    def is_still_connected(d, exclude_node):
        """Check district d remains connected if exclude_node is removed."""
        members = dist_members[d] - {exclude_node}
        if not members:
            return False
        subgraph = G.subgraph(members)
        return nx.is_connected(subgraph)

    max_rounds = 200
    swaps_total = 0
    for rnd in range(max_rounds):
        over  = [d for d in range(N_SEATS) if district_pops[d] > hi]
        under = [d for d in range(N_SEATS) if district_pops[d] < lo]
        if not over and not under:
            break

        swaps_this_round = 0
        for d_over in over:
            if district_pops[d_over] <= hi:
                continue
            # Find border nodes of d_over adjacent to an under-populated district
            for node in list(border_nodes(d_over)):
                node_pop = G.nodes[node]["population"]
                # Which under district neighbours this node?
                for nb in G.neighbors(node):
                    d_nb = assignment[nb]
                    if d_nb == d_over:
                        continue
                    if district_pops[d_nb] >= hi:
                        continue
                    # Would the transfer keep both within bounds?
                    new_over = district_pops[d_over] - node_pop
                    new_nb   = district_pops[d_nb]   + node_pop
                    if new_over < lo or new_nb > hi:
                        continue
                    # Would d_over stay connected?
                    if not is_still_connected(d_over, node):
                        continue
                    # Execute swap
                    assignment[node]          = d_nb
                    dist_members[d_over].discard(node)
                    dist_members[d_nb].add(node)
                    district_pops[d_over]     = new_over
                    district_pops[d_nb]       = new_nb
                    swaps_this_round         += 1
                    swaps_total              += 1
                    break
                if district_pops[d_over] <= hi:
                    break

        if swaps_this_round == 0:
            break

    still_over  = sum(1 for d in range(N_SEATS) if district_pops[d] > hi)
    still_under = sum(1 for d in range(N_SEATS) if district_pops[d] < lo)
    elapsed = time.time() - t0
    print(f"  Phase 2 done in {elapsed:.1f}s  |  {swaps_total} swaps  |  "
          f"out-of-band: {still_over} over, {still_under} under")
    print(f"  Population range: {min(district_pops):,} – {max(district_pops):,}  "
          f"(ideal: {ideal:,.0f})")

    if still_over or still_under:
        print(f"  ⚠  Some districts still out of band — widening tolerance to 10% for init.")
        # Widen tolerance flag for the MCMC initialiser
        G.graph["wide_init_tolerance"] = True

    from collections import Counter
    counts = Counter(assignment.values())
    print(f"  Districts: {len(counts):,}  |  "
          f"counties/dist: {min(counts.values())}–{max(counts.values())}")

    gc_graph = GCGraph(G)
    return gc_graph, assignment


def run_mcmc(gc_graph, initial_assignment, ideal):
    print(f"\n[4/5] Running ReCom MCMC — {N_STEPS:,} steps ...")
    import functools
    from gerrychain import MarkovChain, Partition
    from gerrychain.proposals import recom
    from gerrychain.updaters import Tally, cut_edges
    from gerrychain.tree import bipartition_tree

    updaters = {
        "population": Tally("population", alias="population"),
        "cut_edges":  cut_edges,
    }

    initial_partition = Partition(
        gc_graph,
        assignment=initial_assignment,
        updaters=updaters,
    )

    # Allow pair reselection so the chain skips district pairs where no
    # balanced cut exists (common when the seed has extreme population imbalance)
    robust_bipartition = functools.partial(
        bipartition_tree,
        allow_pair_reselection=True,
    )

    def proposal(p):
        try:
            return recom(
                p,
                pop_col="population",
                pop_target=ideal,
                epsilon=POPULATION_TOLERANCE,
                node_repeats=2,
                method=robust_bipartition,
            )
        except (IndexError, RuntimeError):
            return p

    chain = MarkovChain(
        proposal=proposal,
        constraints=[lambda p: True],
        accept=lambda p: True,
        initial_state=initial_partition,
        total_steps=N_STEPS,
    )

    best        = initial_partition
    best_cut    = len(initial_partition["cut_edges"])
    initial_cut = best_cut
    stats       = []
    t0          = time.time()
    log_every   = max(1, N_STEPS // 25)

    print(f"\n  {'Step':>7}  {'Cut edges':>10}  {'Best':>8}  {'Elapsed':>10}")
    print(f"  {'----':>7}  {'---------':>10}  {'----':>8}  {'---------':>10}")

    for i, partition in enumerate(chain):
        n_cut = len(partition["cut_edges"])
        stats.append((i, n_cut))
        if n_cut < best_cut:
            best_cut = n_cut
            best     = partition
        if i % log_every == 0 or i == N_STEPS - 1:
            elapsed = time.time() - t0
            rate    = i / elapsed if i > 0 else 0
            eta     = f"ETA {(N_STEPS-i)/rate/60:.1f}m" if rate > 0 else ""
            print(f"  {i:>7,}  {n_cut:>10,}  {best_cut:>8,}  {elapsed:>9.1f}s  {eta}")

    elapsed     = time.time() - t0
    improvement = (initial_cut - best_cut) / initial_cut * 100
    print(f"\n  Finished in {elapsed/60:.1f} min  |  "
          f"Cut edges: {initial_cut:,} -> {best_cut:,}  "
          f"({improvement:.1f}% improvement)")
    return best, stats


def save_outputs(best_partition, G, chain_stats, ideal):
    print("\n[5/5] Saving outputs …")

    assignment    = dict(best_partition.assignment)
    pop_by_dist   = dict(best_partition["population"])

    # per-county CSV
    rows_county = []
    for node in G.nodes():
        rows_county.append({
            'fips':       node,
            'name':       G.nodes[node]['name'],
            'state':      G.nodes[node]['state'],
            'district':   int(assignment.get(node, 0)) + 1,
            'population': G.nodes[node]['population'],
        })
    rows_county.sort(key=lambda r: (r['district'], r['name']))
    p = os.path.join(OUTPUT_DIR, 'uda_counties.csv')
    with open(p, 'w', newline='') as f:
        w = csv.DictWriter(f, fieldnames=['fips','name','state','district','population'])
        w.writeheader(); w.writerows(rows_county)
    print(f"  Saved: {p}")

    # per-district summary
    dist_states = defaultdict(set)
    dist_n      = defaultdict(int)
    for node in G.nodes():
        d = assignment.get(node, 0)
        dist_states[d].add(G.nodes[node]['state'])
        dist_n[d] += 1

    rows_dist = []
    for d, pop in sorted(pop_by_dist.items()):
        rows_dist.append({
            'district':         int(d) + 1,
            'population':       int(pop),
            'ideal':            round(ideal),
            'deviation_pct':    round((pop - ideal) / ideal * 100, 3),
            'n_counties':       dist_n[d],
            'n_states_crossed': len(dist_states[d]),
            'states':           '|'.join(sorted(dist_states[d])),
        })
    p = os.path.join(OUTPUT_DIR, 'uda_summary.csv')
    with open(p, 'w', newline='') as f:
        w = csv.DictWriter(f, fieldnames=rows_dist[0].keys())
        w.writeheader(); w.writerows(rows_dist)
    print(f"  Saved: {p}")

    # MCMC diagnostics
    p = os.path.join(OUTPUT_DIR, 'uda_chain_stats.csv')
    with open(p, 'w', newline='') as f:
        w = csv.writer(f); w.writerow(['step','cut_edges']); w.writerows(chain_stats)
    print(f"  Saved: {p}")

    # Statistics
    pops = [r['population'] for r in rows_dist]
    devs = [r['deviation_pct'] for r in rows_dist]
    print(f"\n  ── Population Balance ──────────────────────────────")
    print(f"  Ideal district size:      {ideal:>12,.0f}")
    print(f"  Min district population:  {min(pops):>12,}  ({min(devs):.3f}%)")
    print(f"  Max district population:  {max(pops):>12,}  (+{max(devs):.3f}%)")
    print(f"  Mean |deviation|:         {np.mean(np.abs(devs)):>12.4f}%")
    print(f"  Within ±1% of ideal:      "
          f"{sum(1 for d in devs if abs(d)<1):>5} of {N_SEATS}")
    print(f"  Crossing ≥1 state line:   "
          f"{sum(1 for r in rows_dist if r['n_states_crossed']>1):>5} of {N_SEATS}")

    # Map
    print("\n  Rendering map …", end=" ", flush=True)
    _render_map(G, assignment, rows_dist, chain_stats, ideal)
    return rows_dist


def _render_map(G, assignment, rows_dist, chain_stats, ideal):
    fig = plt.figure(figsize=(22, 11), facecolor='#0d1117')
    gs  = fig.add_gridspec(2, 3, width_ratios=[3, 1, 1],
                           height_ratios=[3, 1], hspace=0.35, wspace=0.3)

    ax_map   = fig.add_subplot(gs[:, 0])
    ax_hist  = fig.add_subplot(gs[0, 1])
    ax_chain = fig.add_subplot(gs[0, 2])
    ax_text  = fig.add_subplot(gs[1, 1:])

    for ax in [ax_map, ax_hist, ax_chain, ax_text]:
        ax.set_facecolor('#161b22')

    cmap20 = cm.get_cmap('tab20', 20)

    # ── Geographic scatter map ──
    node_x, node_y, node_c = [], [], []
    rng_jitter = np.random.default_rng(SEED)
    for node in G.nodes():
        state = G.nodes[node]['state']
        lon, lat = STATE_LOC.get(state, (-98, 38))
        jx = rng_jitter.uniform(-1.5, 1.5)
        jy = rng_jitter.uniform(-1.0, 1.0)
        d  = assignment.get(node, 0)
        node_x.append(lon + jx)
        node_y.append(lat + jy)
        node_c.append(cmap20(d % 20))

    # Draw edges (very faint)
    for u, v in G.edges():
        nodes_list = list(G.nodes())
        # Skip for performance — too many edges to draw individually
        pass

    ax_map.scatter(node_x, node_y, c=node_c, s=6, alpha=0.75,
                   linewidths=0, rasterized=True)
    ax_map.set_xlim(-128, -65)
    ax_map.set_ylim(24, 51)
    ax_map.set_facecolor('#0d1117')
    ax_map.set_title(
        'United Districts of America — 435 Congressional Districts\n'
        'County-level ReCom MCMC · 48 Contiguous States · State Lines Ignored',
        color='white', fontsize=12, fontfamily='monospace', pad=8,
    )
    ax_map.tick_params(colors='#555566', labelsize=7)
    ax_map.set_xlabel('Longitude', color='#555566', fontsize=7)
    ax_map.set_ylabel('Latitude',  color='#555566', fontsize=7)
    for spine in ax_map.spines.values():
        spine.set_edgecolor('#222233')

    # ── Population deviation histogram ──
    devs = [r['deviation_pct'] for r in rows_dist]
    ax_hist.hist(devs, bins=35, color='#4fc3f7', edgecolor='#0d1117',
                 linewidth=0.4, alpha=0.9)
    ax_hist.axvline(0, color='#ff7043', linewidth=1.5, linestyle='--', label='Ideal')
    ax_hist.axvline(-POPULATION_TOLERANCE*100, color='#ffcc02',
                    linewidth=1, linestyle=':', alpha=0.7)
    ax_hist.axvline( POPULATION_TOLERANCE*100, color='#ffcc02',
                    linewidth=1, linestyle=':', alpha=0.7, label=f'±{POPULATION_TOLERANCE*100:.0f}%')
    ax_hist.set_title('Population Deviation', color='white', fontsize=9)
    ax_hist.set_xlabel('% from ideal', color='#aaaaaa', fontsize=7)
    ax_hist.set_ylabel('Districts', color='#aaaaaa', fontsize=7)
    ax_hist.tick_params(colors='#888899', labelsize=7)
    ax_hist.legend(fontsize=6, facecolor='#1a1f2e', labelcolor='white',
                   edgecolor='#333344')
    for spine in ax_hist.spines.values():
        spine.set_edgecolor('#222233')

    # ── MCMC trace plot (cut edges over steps) ──
    steps    = [s[0] for s in chain_stats]
    cut_vals = [s[1] for s in chain_stats]
    # Rolling minimum
    rolling_min = []
    cur_min = float('inf')
    for v in cut_vals:
        cur_min = min(cur_min, v)
        rolling_min.append(cur_min)

    ax_chain.plot(steps, cut_vals, color='#4fc3f7', linewidth=0.5,
                  alpha=0.5, label='Cut edges')
    ax_chain.plot(steps, rolling_min, color='#ff7043', linewidth=1.2,
                  label='Running min')
    ax_chain.set_title('MCMC Trace', color='white', fontsize=9)
    ax_chain.set_xlabel('Step', color='#aaaaaa', fontsize=7)
    ax_chain.set_ylabel('Cut edges', color='#aaaaaa', fontsize=7)
    ax_chain.tick_params(colors='#888899', labelsize=7)
    ax_chain.legend(fontsize=6, facecolor='#1a1f2e', labelcolor='white',
                    edgecolor='#333344')
    for spine in ax_chain.spines.values():
        spine.set_edgecolor('#222233')

    # ── Stats text box ──
    pops = [r['population'] for r in rows_dist]
    cross_state = sum(1 for r in rows_dist if r['n_states_crossed'] > 1)
    counties_pd = [r['n_counties'] for r in rows_dist]
    stats = (
        f"  Total population: {sum(pops):,}   |   "
        f"Ideal district: {ideal:,.0f}   |   "
        f"Mean |dev|: {np.mean(np.abs(devs)):.3f}%   |   "
        f"Districts within ±1%: {sum(1 for d in devs if abs(d)<1)}/{N_SEATS}   |   "
        f"Cross-state districts: {cross_state}/{N_SEATS}   |   "
        f"Avg counties/district: {np.mean(counties_pd):.1f}"
    )
    ax_text.text(0.5, 0.5, stats, transform=ax_text.transAxes,
                 ha='center', va='center', fontsize=8, fontfamily='monospace',
                 color='#ccddff',
                 bbox=dict(boxstyle='round,pad=0.5', facecolor='#1a2035',
                           edgecolor='#334466', alpha=0.9))
    ax_text.set_axis_off()

    map_path = os.path.join(OUTPUT_DIR, 'uda_map.png')
    plt.savefig(map_path, dpi=150, bbox_inches='tight',
                facecolor=fig.get_facecolor())
    plt.close()
    print(f"done\n  Saved: {map_path}")


# ── Main ───────────────────────────────────────────────────────────────────────

def main():
    print("=" * 64)
    print("  United Districts of America (UDA)")
    print(f"  {N_SEATS} seats · 48 states · ReCom MCMC · {N_STEPS:,} steps")
    print(f"  Population tolerance: ±{POPULATION_TOLERANCE*100:.0f}%  |  seed: {SEED}")
    print("=" * 64)

    t0 = time.time()

    G                            = load_adjacency_graph()
    G, total_pop, ideal          = assign_populations(G)
    gc_graph, init_assignment    = seed_partition(G, total_pop)
    best_partition, chain_stats  = run_mcmc(gc_graph, init_assignment, ideal)
    save_outputs(best_partition, G, chain_stats, ideal)

    elapsed = time.time() - t0
    print(f"\n{'='*64}")
    print(f"  Total runtime: {elapsed/60:.1f} minutes")
    print(f"  Outputs: {OUTPUT_DIR}")
    print(f"{'='*64}")


if __name__ == '__main__':
    main()
